// Code generated by boot. DO NOT EDIT.

package dao

import (
	"context"

	model "{{.ModelPkg}}"
	"github.com/Rascal0814/boot/log"
	"github.com/Rascal0814/boot/orm"
	"gorm.io/gorm"
)

type {{.ModelName}}Dao struct {
	db  *gorm.DB
	log *log.Logger
}

func New{{.ModelName}}Dap(db *gorm.DB, log *log.Logger) *{{.ModelName}}Dao {
	return &DishesDao{db: db, log: log}
}

func (dao *{{.ModelName}}Dao) Insert(ctx context.Context, f func(dish *model.{{.ModelName}}) error) (*model.{{.ModelName}}, error) {
	var m model.{{.ModelName}}
	err := f(&m)
	if err != nil {
		return nil, dao.log.Error("insert dish error", err)
	}
	err = dao.db.WithContext(ctx).Create(&m).Error
	if err != nil {
		return nil, dao.log.Error("insert dish error", err)
	}
	return &m, err
}

func (dao *{{.ModelName}}Dao) Get(ctx context.Context, id int64) (*model.{{.ModelName}}, error) {
	var m = &model.{{.ModelName}}{}
	err := dao.db.WithContext(ctx).Where("id = ?", id).Find(m).Error
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (dao *{{.ModelName}}Dao) Del(ctx context.Context, id int64) error {
	err := dao.db.WithContext(ctx).Where("id = ?", id).Delete(&model.{{.ModelName}}{}).Error
	if err != nil {
		return dao.log.Error("del dish error", err)
	}
	return nil
}

func (dao *{{.ModelName}}Dao) List(ctx context.Context,p *orm.Pager) ([]*model.{{.ModelName}}, int64, error) {
	var res = make([]*model.{{.ModelName}}, 0)
	var total int64
	err := dao.db.WithContext(ctx).Model(&model.{{.ModelName}}{}).Count(&total).Limit(int((p.PageIndex) * p.PageSize)).Offset(int(p.PageIndex - 1)).Find(&res).Error
	if err != nil {
		return nil, 0, dao.log.Error("get dish list error", err)
	}
	return res, total, nil
}

func (dao *{{.ModelName}}Dao) Update(ctx context.Context, m *model.{{.ModelName}}) (*model.{{.ModelName}}, error) {
	err := dao.db.WithContext(ctx).Updates(m).Error
	if err != nil {
		return nil, dao.log.Error("update dish error", err)
	}
	return m, nil
}
